version: '3.8'

services:
  frontend:
    image: ankushbehl/s3-browser-frontend:latest
   # build:
   #   context: ./frontend
    ports:
      - "8080:8080"
    # depends_on:
    #   - backend

  backend:
   # build:
   #   context: ./backend
    image: ankushbehl/s3-browser-backend:latest
    ports:
      - "5000:5000"
